#!/usr/bin/env bash
set -euo pipefail
export CLAUDE_PLUGIN_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
source "$CLAUDE_PLUGIN_ROOT/scripts/lib/state.sh"

SCHEMA="$CLAUDE_PLUGIN_ROOT/schemas/generated_files.schema.json"
tmpdir=$(mktemp -d)

cat > "$tmpdir/ok.json" <<'EOF'
{
  "repo": "apache/airflow",
  "generated_at": "2026-04-24T11:45:00Z",
  "entries": [
    {
      "path": "airflow/api_fastapi/core_api/openapi/v1-generated.yaml",
      "marker": "AUTO-GENERATED",
      "regenerate_cmd": "pre-commit run update-openapi-spec --all-files"
    },
    {
      "path": "providers/google/src/airflow/providers/google/cloud/openlineage/_proto_pb2.py",
      "marker": "@generated by the protocol buffer compiler",
      "regenerate_cmd": null
    }
  ]
}
EOF
validate_json "$SCHEMA" "$tmpdir/ok.json" || { echo "FAIL valid"; exit 1; }

echo '{}' > "$tmpdir/bad.json"
validate_json "$SCHEMA" "$tmpdir/bad.json" 2>/dev/null && { echo "FAIL bad accepted"; exit 1; }

echo "OK test_schema_generated_files.sh"
